default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'op2_dev') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'op2_test') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'op2_production') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'op2_prod') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'op2_prod') %>
